### PR TITLE
Fix reputables count

### LINKED ISSUE #117: reputables count is wrong
The number of reputables is reported as 244 which seems terribly wrong when looking at the data.

currently we are in attesting phase of cindex 25

I dumped the `encointerCeremonies.participantReputation` registry for cindex 20-24 using js/apps. checked that 19 is empty indeed
https://gist.github.com/brenzi/46aae68e611ea843b2b0dc776fb99b3f

I process this data as follows:

extract accountid's only:
```
> sed -n '/digest/{ n; n; n; n; p }' reputables-20-24.txt > reputables-multi.txt
> wc -l reputables-multi.txt
197 reputables-multi.txt
```
so, we have 197 reputations, counting each attendance of all attendees

but we want to know the number of UNIQUE accounts:

```
> sort reputables-multi.txt | uniq | wc -l
85
```

So, we actually only have 85 reputables currently. no idea where the 244 come from

### PR DESCRIPTION
**Pull request by clangenb**
Closes #117.

There were multiple issues:
1. The `keys()` getter of the storage map does not return the account id itself but the full key, which prevented making a set out of it: https://polkadot.js.org/docs/api/start/api.query.other/#map-keys--entries
2. JavaScript objects are only equal if they point to the same reference.

The current count in the explorer is now 95 for the Zurich community (compared to the 85 that were in @brenzi's gist), which is plausible as a few newbies might have got reputation now:

image

### CODE REVIEW

File: src/map/MapSidebar.js [hunk 1]
```diff
@@ -105,31 +105,8 @@ function MapSidebarMain (props) {
...
-
-      // reduce the array of arrays to a single set.
-      const allReputablesSet = new Set(arrayOfReputablesArray.reduce((all, nextArray) => [...all, ...nextArray]));
-
-      setAllReputableNumber(allReputablesSet.size);
-    }
-    getReputableCount();
-  }, [api, cid]);
+    getAllReputables(api, cid, debug).then((reputables) => setAllReputableNumber([reputables.length]));
+  }, [api, cid, debug]);
```
Comment (clangenb) [inline src/map/MapSidebar.js:109]: @Jay-Forrer 

This is how I want to have the code structure. The use `effectEffect` calls a single function or maybe two or three functions that are stateless aka everything they need is supplied as a function arg. Then the return value of those functions can be use for the `setEffects` function
