### PR TITLE
Number of last and current Meetups and Number of last and current participant Count is shown incorrectly

### LINKED ISSUE #113: community info not correct during registering phase
image

issues:
* [x] MEETUPS ASSIGNED IN LAST CEREMONY: 0 is wrong
* [x] PARTICIPANTS REGISTERED IN LAST CEREMONY: 0 is wrong
* [x] PARTICIPANTS REGISTERED: 0 is wrong (should be the sum of all categories displayed above)
* [x] MEETUPS ASSIGNED: 0 : it should not say 0. either hide this field or say "awaiting..."....
* [x] tentative community growth could be calculated and should be, even if we don't check the rules for assignment

### PR DESCRIPTION
**Pull request by Jay-Forrer**
closes #113

### CODE REVIEW

File: src/map/MapSidebar.js [hunk 1]
```diff
@@ -125,20 +125,26 @@ function MapSidebarMain (props) {
...
 
-      const [assignmentCounts, endorsees] = await Promise.all([
+      const [assignmentCounts, endorsees, tempNewbies] = await Promise.all([
         api.query.encointerCeremonies.assignmentCounts(currentCommunityCeremony),
-        api.query.encointerCeremonies.endorseeCount(currentCommunityCeremony)
+        api.query.encointerCeremonies.endorseeCount(currentCommunityCeremony),
+        api.query.encointerCeremonies.newbieCount(currentCommunityCeremony)
       ]);
+      let newbies;
+      if (currentPhase === 0) {
```
Comment (brenzi) [inline src/map/MapSidebar.js:134]: no hardcoded indices. should be constant or enum

**Review by brenzi — CHANGES_REQUESTED** [review]
tested. does fix the issue

File: src/map/MapSidebar.js (hunk 1 above)
Comment (brenzi) [reply src/map/MapSidebar.js:134]: I realized that this is not done nicely in other places in the code, need cleanup later. will merge this

Comment (brenzi) [reply src/map/MapSidebar.js:134]: should use `.isRegistering` as defined in types

**Review by brenzi — APPROVED** [review]
